//
// Created by fquinn on 26/06/2018.
//

#ifndef OPENMAMA_SNAPSHOT_RESTREQUESTHANDLER_H
#define OPENMAMA_SNAPSHOT_RESTREQUESTHANDLER_H


class RestRequestHandler {

};


#endif //OPENMAMA_SNAPSHOT_RESTREQUESTHANDLER_H
